### PR TITLE
CHANGELOG.md: udpate 4.8.0.2 info

### PR DESCRIPTION
**Pull request by miczyg1**
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>

### CODE REVIEW

**Comment by miczyg1** [comment]
@pietrushnic I wonder if we should give more information in CHANGELOG. We have not changed anything related to our platforms.

**Comment by pietrushnic** [comment]
@miczyg1 this release is quite small, the value is in test results and upstreaming effort.

**Comment by pietrushnic** [comment]
@miczyg1 yes I'm ok with it. Do you want me to merge?

**Comment by miczyg1** [comment]
@pietrushnic actually i expected just an approval so I would merge it myself

**Pull request merged**
