### PR TITLE
payloads/external/iPXE/menu.ipxe: autoboot starting from last interfa…

### PR DESCRIPTION
**Pull request by miczyg1**
…ce with WoL capability

Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>

### CODE REVIEW

**Comment by miczyg1** [comment]
iPXE and Linux enumerates the NICs in reversed order. The interface with WoL capability gets the last index after enumeration. iPXE autoboot starts always from net0. Start autoboot from the last device instead. Related thread:

http://pcengines.info/forums/?page=post&id=1327A21F-5B1A-47D3-9A98-116CA1A464F1&fid=DF5ACB70-99C4-4C61-AFA6-4C0E0DB05B2A

@michaelsteinmann are there any customers which must use net0 interface (the one closer to COM1 connector) in their production systems? I would like to avoid any inconvenience.

**Comment by miczyg1** [comment]
It is dangerous to change the behavior after that many years after introduction of the board. Closed

**Comment by pietrushnic** [comment]
@miczyg1 can we make it optional through menu?

**Comment by miczyg1** [comment]
@pietrushnic not possible through normal ways. The script is integrated into ipxe binary.

**Pull request closed without merging**
