### PR TITLE
src/mainboard/pcengines/apu1/bootorder: fix pci device paths

### PR DESCRIPTION
**Pull request by miczyg1**
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>

### CODE REVIEW

**Comment by pietrushnic** [comment]
@miczyg1 do we have automated test that can prove without patches it doesn't work and with patches it works?

**Comment by miczyg1** [comment]
@pietrushnic for now I have not created any tests. It is complicated stuff to verify it, because it depends on hardware configuration and number of different types of boot medias. I must think this through still

**Comment by pietrushnic** [comment]
@miczyg1 please add correct JIRA items and I'm fine with mergining it.

**Comment by miczyg1** [comment]
@pietrushnic done

**Pull request merged**
