### PR TITLE
Enable iommu

### PR DESCRIPTION
**Pull request by pietrushnic**

### CODE REVIEW

**Comment by miczyg1** [comment]
@pietrushnic XEN still complains:
```
CPUx: No irq handler for vector e7 (IRQ -2147483648)
```
Situation did not change since last time when I tired these patches.

**Comment by pietrushnic** [comment]
@miczyg1  yes, but there is no hang at this point and I survived 100x reboots. If you google for this IRQ handler you will see that most hardware configuration trigger this error. We probably have to ask Xen people how we can get rid of that.

@kmalkki any ideas what this IRQ handler is and why we don't have it in our firmware?

**Comment by miczyg1** [comment]
@pietrushnic well in my case I didn't survive 100x reboots. Do I have to change pxe IP or something to reproduce Your configuration?

**Comment by pietrushnic** [comment]
@miczyg1 this may be completely unrelated since we facing some thermal problems IIUC. Please try apu2c.

**Comment by miczyg1** [comment]
@pietrushnic problems with production PXE server. On dev PXE works well

**Comment by pietrushnic** [comment]
@miczyg1 if no review from @kmalkki please merge to v4.8.0.3 release.

**Pull request merged**
