### PR TITLE
WIP: Apu5 s1button ml

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by pietrushnic** [comment]
@miczyg1 still WIP?

**Comment by miczyg1** [comment]
@pietrushnic its for mainline now. I left WIP because I don't have the hardware to verify if the change works.

**Comment by pietrushnic** [comment]
@miczyg1 ok let's wait for hardware

**Comment by miczyg1** [comment]
@pietrushnic confirmed to be working. RF test also ready, will push it soon.

**Pull request merged**
