### PR TITLE
src/cpu/amd/pi/00730F01/model_16_init.c: fix incosistent MTRRs

### PR DESCRIPTION
**Pull request by miczyg1**
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>

### CODE REVIEW

**Comment by miczyg1** [comment]
When postcar frame is created, there are BSP MTRRs wit hWB settings pushed onto the stack. These MTRRs from stack are later used in postcar stage to restore the previous state after CAR teardown. However, the order of the MTRRs is not preserved and causes the Linux warning about inconsistent MTRRs. Additionally APs have an UC MTRRs for cbmem, don't know why...

@krystian-hebel do you have ideas how to replicate BSP MTRRs on APs in a better way that it is now?

**Comment by krystian-hebel** [comment]
UC ranges are not saved to the postcar frame: https://github.com/pcengines/coreboot/blob/inconsistent_mtrr_fix/src/drivers/amd/agesa/mtrr_fixme.c#L60

Does BSP even set its MTRRs to those saved in frame, reordered to occupy only the lowest registers? It should, but it is also possible that they are overwritten again by AGESA. In that case the only thing we can do is to redo the same thing (save MTRRs to stack and then read them without holes) after the last call to the AGESA.

Another option would be to save the index of MTRR on the stack, but that could potentially break other platforms...

**Comment by miczyg1** [comment]
@krystian-hebel UC does not land in MTRR postcar frame because it covers the CBMEM. It is used with invd to make cbmem hit the DRAM IIRC, so it is not needed later on.

There are no holes, but the order is different on BSP, that's all. Or I do not quite understand why APs have the UC entry for cbmem, UC MTRR on BSP should be enough. I have cleared the mask because wanted to disable MTRR before changing the base.

**Comment by miczyg1** [comment]
Will be addresses by https://review.coreboot.org/c/coreboot/+/52762

**Pull request closed without merging**
