### PR TITLE
Set tag

### PR DESCRIPTION
**Pull request by pietrushnic**

### CODE REVIEW

**Comment by miczyg1** [comment]
@pietrushnic i'm fine with the change, however should be rebased because of https://github.com/pcengines/coreboot/pull/157#discussion_r192345698

**Comment by pietrushnic** [comment]
@miczyg1 there was incorrect base for that branch

**Comment by miczyg1** [comment]
@pietrushnic I have already merged add_ml_configs branch.

**Comment by pietrushnic** [comment]
@miczyg1 changed to `rel_4.8.0.1`

**Pull request merged**
