### PR TITLE
No SPD option in coreboot menuconfig

### PR DESCRIPTION
**Pull request by miczyg1**
Added option to disable SPD i memtest86+ in coreboot menuconfig. For future use with mainline memtest86+ or use it with our memtest86+ repo on branch gerrit_19053. Merge when changes to Memtest86+ are made.

### CODE REVIEW

**Comment by pietrushnic** [comment]
@miczyg1 commit messages are low quality. Please check mainline coreboot git log, if you plan to push those changes to mainline.

**Comment by miczyg1** [comment]
I will correct the changes here and sync them with coreboot mainline changes when they are merged.

**Comment by mek-x** [comment]
@miczyg1 create PR for the release branch, not the main one. Correct it also for other PRs, please.

**Comment by miczyg1** [comment]
@mek-x we do not have a release branch for legacy. Could You please create one?

**Comment by mek-x** [comment]
@miczyg1 yes, this should do it, thanks. If there is none, you can feel free and create one yourself (notice how they're named). This time I've created one - `rel_v4.0.13`

**Pull request closed without merging**
