### PR TITLE
Revert "Revert "cpu/amd/*/*/acpi/: Use 'Device()' instead of 'Process…

### PR DESCRIPTION
**Pull request by mkopec**
…or()'""

This reverts commit cd26f2a3b68593e2762d3b7617d59c0d03701dd4.

This enables compilation using newer versions of `coreboot-sdk`.

Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

### CODE REVIEW

**Comment by miczyg1** [comment]
There is oen more thing to handle. Patching the processor scope in AGESA SSDT has to be enabled back: https://github.com/pcengines/coreboot/blob/release/src/northbridge/amd/pi/00730F01/northbridge.c#L712
otherwise the SSDT will reference the CPUs in `\_PR` scope. Also I would remove the patching functions and enable the CPUs In SB scope in AGESA: https://github.com/pcengines/coreboot/blob/release/src/vendorcode/amd/pi/00730F01/AGESA.h#L2905
The parameter should be passed to the AmdInitLate: https://github.com/pcengines/coreboot/blob/release/src/northbridge/amd/pi/00730F01/state_machine.c#L58

**Comment by mkopec** [comment]
I re-enabled the processor scope patching and added the parameter `ProcessorScopeInSb` to `state_machine.c` for family14 and 00730F01. This builds and boots Debian successfully on apu1 and apu2.

**Comment by miczyg1** [comment]
@mkopec no ACPI errors in dmesg?

**Comment by mkopec** [comment]
No, I don't see any ACPI errors.

**Review by miczyg1 — APPROVED** [review]

**Pull request merged**
